import { ProjectOpportunity, Client, Employee, MonthlyBilling } from './types';

export const opportunities: ProjectOpportunity[] = [
  // ============================================================
  // STATUS 7 - DELIVERING (Active Projects)
  // ============================================================
  {
    id: '26-402',
    client: 'Kingsway Dynamic',
    date: '2026-01-15',
    opportunity: 'Suministro, Licencia y Soporte Software Insight Data Analysis',
    description: 'Proyecto de análisis de datos avanzado con plataforma Insight para cliente en Singapur. Incluye suministro de licencias, soporte y formación.',
    amount: 2852194.92,
    currency: 'EUR',
    statusCode: 7,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 2852194.92,
    owner: 'FDB',
    country: 'Singapore',
    expectedClosingDate: '2026-12-31',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 2852194.92 },
    acceptanceDate: '2026-01-20',
    costs: 1850000,
    materialCost: 1200000,
    peopleCost: 650000,
    margin: 35.1,
    totalInvoiced: 1200000,
    pendingToInvoice: 1652194.92,
    wipStatus: 42,
    totalPercentage: 100,
    endDate: '2026-12-31',
    observations: 'Proyecto de alto valor en ejecución. Cliente estratégico para expansión en APAC.',
  },
  {
    id: '25-213',
    client: 'SMA',
    date: '2025-03-10',
    opportunity: 'MWC26 booth design + management',
    description: 'Diseño y gestión del stand de SMA en el Mobile World Congress 2026. Incluye diseño creativo, fabricación, logística y gestión durante el evento.',
    amount: 415125,
    currency: 'EUR',
    statusCode: 7,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 415125,
    owner: 'MARIA',
    country: 'Malaysia',
    expectedClosingDate: '2026-03-05',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 415125, proservices: 0 },
    acceptanceDate: '2025-09-15',
    costs: 310000,
    materialCost: 180000,
    peopleCost: 130000,
    margin: 25.3,
    totalInvoiced: 200000,
    pendingToInvoice: 215125,
    wipStatus: 55,
    totalPercentage: 100,
    endDate: '2026-03-10',
    observations: 'Stand MWC26 en Barcelona. Evento clave para el cliente.',
  },
  {
    id: '25-171',
    client: 'RETECH',
    date: '2025-04-20',
    opportunity: 'Desarrollo IA Agentiva para MICE',
    description: 'Desarrollo de plataforma de Inteligencia Artificial Agentiva para el sector MICE (Meetings, Incentives, Conferences, Exhibitions). Automatización de procesos y gestión inteligente.',
    amount: 187661.25,
    currency: 'EUR',
    statusCode: 7,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 187661.25,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2025-12-31',
    businessLines: { hardware: 0, ia: 187661.25, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    acceptanceDate: '2025-05-01',
    costs: 95000,
    materialCost: 20000,
    peopleCost: 75000,
    margin: 49.4,
    totalInvoiced: 140000,
    pendingToInvoice: 47661.25,
    wipStatus: 75,
    totalPercentage: 100,
    endDate: '2025-12-31',
    observations: 'Proyecto IA en fase avanzada. Entrega prevista Q4 2025.',
  },
  {
    id: '25-017',
    client: 'P. Freire',
    date: '2025-01-08',
    opportunity: 'MTI Construcciones Navales P. Freire',
    description: 'Servicios profesionales de consultoría y tecnología para Construcciones Navales P. Freire. Digitalización de procesos de construcción naval.',
    amount: 120962.52,
    currency: 'EUR',
    statusCode: 7,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 120962.52,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2025-12-31',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 120962.52 },
    acceptanceDate: '2025-01-15',
    costs: 72000,
    materialCost: 15000,
    peopleCost: 57000,
    margin: 40.5,
    totalInvoiced: 90000,
    pendingToInvoice: 30962.52,
    wipStatus: 80,
    totalPercentage: 100,
    endDate: '2025-12-31',
    observations: 'Proyecto en curso. Cliente recurrente.',
  },
  {
    id: '25-093',
    client: 'GMV',
    date: '2025-02-14',
    opportunity: 'Ampliaciones SAEATMBCN',
    description: 'Ampliaciones del sistema SAEATM para GMV en Barcelona. Incluye nuevas funcionalidades y módulos de gestión de tráfico aéreo.',
    amount: 60000,
    currency: 'EUR',
    statusCode: 7,
    company: 'BCN',
    probability: 100,
    weightedPipeline: 60000,
    owner: 'JML',
    country: 'Spain',
    expectedClosingDate: '2025-09-30',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 60000 },
    acceptanceDate: '2025-03-01',
    costs: 35000,
    materialCost: 5000,
    peopleCost: 30000,
    margin: 41.7,
    totalInvoiced: 45000,
    pendingToInvoice: 15000,
    wipStatus: 85,
    totalPercentage: 100,
    endDate: '2025-09-30',
    observations: 'Ampliaciones técnicas en curso.',
  },
  {
    id: '25-008',
    client: 'Worldsensing',
    date: '2025-01-05',
    opportunity: 'Worldsensing outsourcing HR ADI',
    description: 'Servicios de outsourcing de recursos humanos para Worldsensing. Gestión y coordinación de equipo técnico dedicado.',
    amount: 65880,
    currency: 'EUR',
    statusCode: 7,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 65880,
    owner: 'ADI',
    country: 'Spain',
    expectedClosingDate: '2025-12-31',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 65880 },
    acceptanceDate: '2025-01-10',
    costs: 52000,
    materialCost: 0,
    peopleCost: 52000,
    margin: 21.1,
    totalInvoiced: 52000,
    pendingToInvoice: 13880,
    wipStatus: 82,
    totalPercentage: 100,
    endDate: '2025-12-31',
    observations: 'Contrato de outsourcing anual. Renovable.',
  },
  {
    id: '26-000',
    client: 'FMB',
    date: '2026-01-02',
    opportunity: 'Manteniment Preventiu/Correctiu Tram Nord L9/L10',
    description: 'Mantenimiento preventivo y correctivo del sistema de tramvia en las líneas Nord L9 y L10 de Barcelona.',
    amount: 69303,
    currency: 'EUR',
    statusCode: 7,
    company: 'BCN',
    probability: 100,
    weightedPipeline: 69303,
    owner: 'CARLES',
    country: 'Spain',
    expectedClosingDate: '2026-12-31',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 69303 },
    acceptanceDate: '2026-01-05',
    costs: 48000,
    materialCost: 15000,
    peopleCost: 33000,
    margin: 30.7,
    totalInvoiced: 30000,
    pendingToInvoice: 39303,
    wipStatus: 35,
    totalPercentage: 100,
    endDate: '2026-12-31',
    observations: 'Contrato de mantenimiento anual con FMB.',
  },
  {
    id: '25-208',
    client: 'FC Barcelona',
    date: '2025-05-20',
    opportunity: 'BIM 2 GMAO (Fase II)',
    description: 'Segunda fase del proyecto BIM to GMAO para FC Barcelona. Integración del gemelo digital BIM con el sistema de gestión de mantenimiento.',
    amount: 99900,
    currency: 'EUR',
    statusCode: 7,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 99900,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2025-12-31',
    businessLines: { hardware: 0, ia: 0, bim: 99900, ttioOm: 0, events: 0, proservices: 0 },
    acceptanceDate: '2025-06-01',
    costs: 55000,
    materialCost: 8000,
    peopleCost: 47000,
    margin: 44.9,
    totalInvoiced: 65000,
    pendingToInvoice: 34900,
    wipStatus: 70,
    totalPercentage: 100,
    endDate: '2025-12-31',
    observations: 'Fase II del proyecto BIM/GMAO. Continuación exitosa de Fase I.',
  },
  {
    id: '26-447',
    client: 'Worldsensing',
    date: '2026-02-10',
    opportunity: 'Servicios de Apoyo para Desarrollo de Negocio en 2026',
    description: 'Servicios de apoyo estratégico para el desarrollo de negocio de Worldsensing durante 2026. Consultoría, análisis de mercado y soporte comercial.',
    amount: 164300,
    currency: 'EUR',
    statusCode: 7,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 164300,
    owner: 'JML',
    country: 'Spain',
    expectedClosingDate: '2026-12-31',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 164300 },
    acceptanceDate: '2026-02-15',
    costs: 95000,
    materialCost: 10000,
    peopleCost: 85000,
    margin: 42.2,
    totalInvoiced: 65000,
    pendingToInvoice: 99300,
    wipStatus: 40,
    totalPercentage: 100,
    endDate: '2026-12-31',
    observations: 'Contrato de servicios anuales 2026.',
  },
  {
    id: '26-464',
    client: 'P. Freire',
    date: '2026-03-05',
    opportunity: 'ILS Rodman Patrulleras',
    description: 'Servicios de Integrated Logistics Support (ILS) para el proyecto de patrulleras Rodman de P. Freire. Documentación técnica y soporte logístico.',
    amount: 103360,
    currency: 'EUR',
    statusCode: 7,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 103360,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-09-30',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 103360 },
    acceptanceDate: '2026-03-10',
    costs: 62000,
    materialCost: 12000,
    peopleCost: 50000,
    margin: 40.0,
    totalInvoiced: 40000,
    pendingToInvoice: 63360,
    wipStatus: 38,
    totalPercentage: 100,
    endDate: '2026-09-30',
    observations: 'Nuevo contrato ILS con P. Freire para proyecto naval.',
  },
  {
    id: '26-439',
    client: 'NIS',
    date: '2026-02-28',
    opportunity: 'NIS Servers Quote',
    description: 'Suministro de servidores y equipamiento de hardware para NIS en Kenya.',
    amount: 10112,
    currency: 'EUR',
    statusCode: 7,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 10112,
    owner: 'DANI A',
    country: 'Kenya',
    expectedClosingDate: '2026-04-30',
    businessLines: { hardware: 10112, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    acceptanceDate: '2026-03-01',
    costs: 7800,
    materialCost: 7800,
    peopleCost: 0,
    margin: 22.9,
    totalInvoiced: 10112,
    pendingToInvoice: 0,
    wipStatus: 100,
    totalPercentage: 100,
    endDate: '2026-04-30',
    observations: 'Suministro completado. Facturado.',
  },

  // ============================================================
  // STATUS 5 - CONTRACT NEGOTIATION
  // ============================================================
  {
    id: '26-405',
    client: 'SAGALES',
    date: '2026-01-20',
    opportunity: 'Diseño y Fabricación Totem Marquesinas (200 Ud)',
    description: 'Diseño, fabricación e instalación de 200 unidades de tótem para marquesinas de autobús. Incluye pantallas digitales y conectividad.',
    amount: 960000,
    currency: 'EUR',
    statusCode: 5,
    company: 'MTI',
    probability: 70,
    weightedPipeline: 672000,
    owner: 'JML',
    country: 'Spain',
    expectedClosingDate: '2026-06-30',
    businessLines: { hardware: 960000, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 680000,
    materialCost: 600000,
    peopleCost: 80000,
    margin: 29.2,
    totalInvoiced: 0,
    pendingToInvoice: 960000,
    wipStatus: 0,
    totalPercentage: 70,
    endDate: '2026-12-31',
    observations: 'Negociación avanzada. Pendiente firma contrato.',
  },
  {
    id: '25-229',
    client: 'INETUM',
    date: '2025-07-10',
    opportunity: 'Instalacion Pupitre, Validadora y Sistema Central Bilbobus',
    description: 'Instalación completa de pupitres de conductor, validadoras y sistema central de gestión para la red de autobuses Bilbobus.',
    amount: 770154,
    currency: 'EUR',
    statusCode: 5,
    company: 'MTI',
    probability: 65,
    weightedPipeline: 500600.1,
    owner: 'JML',
    country: 'Spain',
    expectedClosingDate: '2026-05-31',
    businessLines: { hardware: 770154, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 540000,
    materialCost: 480000,
    peopleCost: 60000,
    margin: 29.9,
    totalInvoiced: 0,
    pendingToInvoice: 770154,
    wipStatus: 0,
    totalPercentage: 65,
    endDate: '2027-06-30',
    observations: 'Proyecto de gran envergadura. Negociación en curso con INETUM.',
  },
  {
    id: '25-157',
    client: 'FC Barcelona',
    date: '2025-04-05',
    opportunity: 'Servicios Profesionales Implantacion Digital Twin',
    description: 'Implementación completa de gemelo digital para el Spotify Camp Nou. Incluye modelado BIM, integración IoT y plataforma de gestión.',
    amount: 720000,
    currency: 'EUR',
    statusCode: 5,
    company: 'MTI',
    probability: 75,
    weightedPipeline: 540000,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-04-30',
    businessLines: { hardware: 0, ia: 360000, bim: 360000, ttioOm: 0, events: 0, proservices: 0 },
    costs: 380000,
    materialCost: 50000,
    peopleCost: 330000,
    margin: 47.2,
    totalInvoiced: 0,
    pendingToInvoice: 720000,
    wipStatus: 0,
    totalPercentage: 75,
    endDate: '2027-12-31',
    observations: 'Proyecto estratégico con FCB. Negociación final.',
  },
  {
    id: '25-121',
    client: 'Diputacio Tarragona',
    date: '2025-03-15',
    opportunity: 'Contadores Agua Municipios-Plataforma Diputación',
    description: 'Suministro e instalación de contadores de agua inteligentes para municipios de la Diputación de Tarragona. Incluye plataforma de gestión centralizada.',
    amount: 1680000,
    currency: 'EUR',
    statusCode: 5,
    company: 'MTI',
    probability: 60,
    weightedPipeline: 1008000,
    owner: 'DANI',
    country: 'Spain',
    expectedClosingDate: '2026-06-30',
    businessLines: { hardware: 840000, ia: 0, bim: 0, ttioOm: 840000, events: 0, proservices: 0 },
    costs: 1100000,
    materialCost: 900000,
    peopleCost: 200000,
    margin: 34.5,
    totalInvoiced: 0,
    pendingToInvoice: 1680000,
    wipStatus: 0,
    totalPercentage: 60,
    endDate: '2027-12-31',
    observations: 'Gran proyecto IoT con Diputación. Proceso licitación en curso.',
  },
  {
    id: '26-465',
    client: 'GMV',
    date: '2026-03-10',
    opportunity: 'Instalacion Telemetria y Letreros Exteriores',
    description: 'Instalación de sistema de telemetría y letreros exteriores para flota de transporte público gestionada por GMV.',
    amount: 190080,
    currency: 'EUR',
    statusCode: 5,
    company: 'BCN',
    probability: 80,
    weightedPipeline: 152064,
    owner: 'JML',
    country: 'Spain',
    expectedClosingDate: '2026-06-15',
    businessLines: { hardware: 190080, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 130000,
    materialCost: 110000,
    peopleCost: 20000,
    margin: 31.6,
    totalInvoiced: 0,
    pendingToInvoice: 190080,
    wipStatus: 0,
    totalPercentage: 80,
    endDate: '2026-12-31',
    observations: 'Propuesta técnica aceptada. Pendiente aprobación presupuestaria.',
  },
  {
    id: '26-461',
    client: 'Cardiology Center Qarshi',
    date: '2026-03-08',
    opportunity: 'Cambio de Tubo Rayos X',
    description: 'Suministro e instalación de nuevo tubo de rayos X para el equipo de diagnóstico del Centro de Cardiología de Qarshi, Uzbekistán.',
    amount: 225000,
    currency: 'EUR',
    statusCode: 5,
    company: 'MTI ARABIA',
    probability: 55,
    weightedPipeline: 123750,
    owner: 'DANI',
    country: 'Uzbekistan',
    expectedClosingDate: '2026-07-31',
    businessLines: { hardware: 225000, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 170000,
    materialCost: 165000,
    peopleCost: 5000,
    margin: 24.4,
    totalInvoiced: 0,
    pendingToInvoice: 225000,
    wipStatus: 0,
    totalPercentage: 55,
    endDate: '2026-09-30',
    observations: 'Equipamiento médico en Uzbekistán. Negociación con cliente final.',
  },
  {
    id: '26-460',
    client: 'Fundacio Montilivi',
    date: '2026-03-05',
    opportunity: 'Digitalización Residencias',
    description: 'Proyecto de digitalización integral de residencias de la Fundació Montilivi. Plataforma IA para gestión de residentes y automatización de servicios.',
    amount: 34354.32,
    currency: 'EUR',
    statusCode: 5,
    company: 'MTI',
    probability: 85,
    weightedPipeline: 29201.17,
    owner: 'DANI',
    country: 'Spain',
    expectedClosingDate: '2026-05-31',
    businessLines: { hardware: 0, ia: 34354.32, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 20000,
    materialCost: 3000,
    peopleCost: 17000,
    margin: 41.8,
    totalInvoiced: 0,
    pendingToInvoice: 34354.32,
    wipStatus: 0,
    totalPercentage: 85,
    endDate: '2026-09-30',
    observations: 'Propuesta aceptada. Tramitación contrato.',
  },
  {
    id: '26-458',
    client: 'Merchant Union',
    date: '2026-02-25',
    opportunity: 'MU Igape 2026',
    description: 'Proyecto de desarrollo IA para Merchant Union con financiación IGAPE 2026. Plataforma de inteligencia artificial para comercio y distribución.',
    amount: 102100,
    currency: 'EUR',
    statusCode: 5,
    company: 'MTI',
    probability: 70,
    weightedPipeline: 71470,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-06-30',
    businessLines: { hardware: 0, ia: 102100, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 65000,
    materialCost: 10000,
    peopleCost: 55000,
    margin: 36.3,
    totalInvoiced: 0,
    pendingToInvoice: 102100,
    wipStatus: 0,
    totalPercentage: 70,
    endDate: '2026-12-31',
    observations: 'Pendiente resolución convocatoria IGAPE.',
  },

  // ============================================================
  // STATUS 4 - SOLUTION DEFINITION
  // ============================================================
  {
    id: '26-100',
    client: 'Telbina',
    date: '2026-01-10',
    opportunity: 'Smart Villages platform & Use Cases',
    description: 'Plataforma integral Smart Villages con casos de uso IoT para municipios rurales en Malaysia. Incluye conectividad, sensórica y plataforma de gestión.',
    amount: 800000,
    currency: 'EUR',
    statusCode: 4,
    company: 'MTI',
    probability: 40,
    weightedPipeline: 320000,
    owner: 'JORDI POL',
    country: 'Malaysia',
    expectedClosingDate: '2026-09-30',
    businessLines: { hardware: 400000, ia: 400000, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 520000,
    materialCost: 320000,
    peopleCost: 200000,
    margin: 35.0,
    totalInvoiced: 0,
    pendingToInvoice: 800000,
    wipStatus: 0,
    totalPercentage: 40,
    endDate: '2027-12-31',
    observations: 'Definición de solución en curso. Reuniones técnicas semanales.',
  },
  {
    id: '26-101-telbina',
    client: 'Telbina',
    date: '2026-01-15',
    opportunity: 'Smart City Bintulu',
    description: 'Proyecto de ciudad inteligente para Bintulu, Malaysia. Plataforma integrada de gestión urbana con IA, IoT y analytics.',
    amount: 1000000,
    currency: 'EUR',
    statusCode: 4,
    company: 'MTI',
    probability: 35,
    weightedPipeline: 350000,
    owner: 'JORDI POL',
    country: 'Malaysia',
    expectedClosingDate: '2026-12-31',
    businessLines: { hardware: 500000, ia: 500000, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 650000,
    materialCost: 400000,
    peopleCost: 250000,
    margin: 35.0,
    totalInvoiced: 0,
    pendingToInvoice: 1000000,
    wipStatus: 0,
    totalPercentage: 35,
    endDate: '2028-12-31',
    observations: 'Gran proyecto Smart City. Requiere soporte gubernamental.',
  },
  {
    id: '26-208',
    client: 'CRCC',
    date: '2026-02-01',
    opportunity: 'Jeddah Smart Digital Twin',
    description: 'Gemelo digital para el proyecto de desarrollo urbano en Jeddah. Integración BIM con plataforma IA para gestión inteligente de infraestructura.',
    amount: 870000,
    currency: 'USD',
    statusCode: 4,
    company: 'MTI ARABIA',
    probability: 30,
    weightedPipeline: 261000,
    owner: 'CHADI',
    country: 'Saudi Arabia',
    expectedClosingDate: '2026-10-31',
    businessLines: { hardware: 0, ia: 435000, bim: 435000, ttioOm: 0, events: 0, proservices: 0 },
    costs: 570000,
    materialCost: 80000,
    peopleCost: 490000,
    margin: 34.5,
    totalInvoiced: 0,
    pendingToInvoice: 870000,
    wipStatus: 0,
    totalPercentage: 30,
    endDate: '2027-12-31',
    observations: 'Proyecto NEOM adyacente. Gran oportunidad en Arabia.',
  },
  {
    id: '26-209',
    client: 'CRCC',
    date: '2026-02-05',
    opportunity: 'Corporate Academy Dhahran Digital Twin',
    description: 'Digital Twin para la Corporate Academy en Dhahran. Modelado completo del campus con integración de sistemas de gestión.',
    amount: 750000,
    currency: 'USD',
    statusCode: 4,
    company: 'MTI ARABIA',
    probability: 30,
    weightedPipeline: 225000,
    owner: 'CHADI',
    country: 'Saudi Arabia',
    expectedClosingDate: '2026-10-31',
    businessLines: { hardware: 0, ia: 375000, bim: 375000, ttioOm: 0, events: 0, proservices: 0 },
    costs: 490000,
    materialCost: 70000,
    peopleCost: 420000,
    margin: 34.7,
    totalInvoiced: 0,
    pendingToInvoice: 750000,
    wipStatus: 0,
    totalPercentage: 30,
    endDate: '2027-12-31',
    observations: 'Segundo proyecto con CRCC en Arabia Saudí.',
  },
  {
    id: '26-101-dbku',
    client: 'DBKU',
    date: '2026-02-20',
    opportunity: 'Smart City Platform Kuching',
    description: 'Plataforma Smart City para Kuching, Sarawak. Sistema centralizado de gestión urbana con IA y análisis de datos.',
    amount: 50000,
    currency: 'EUR',
    statusCode: 4,
    company: 'MTI',
    probability: 45,
    weightedPipeline: 22500,
    owner: 'JORDI POL',
    country: 'Malaysia',
    expectedClosingDate: '2026-08-31',
    businessLines: { hardware: 0, ia: 50000, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 30000,
    materialCost: 5000,
    peopleCost: 25000,
    margin: 40.0,
    totalInvoiced: 0,
    pendingToInvoice: 50000,
    wipStatus: 0,
    totalPercentage: 45,
    endDate: '2026-12-31',
    observations: 'Fase piloto Smart City Kuching. Posible ampliación.',
  },
  {
    id: '25-235',
    client: 'ORECO',
    date: '2025-08-10',
    opportunity: 'Generador de Ofertas Oreco',
    description: 'Desarrollo de sistema generador automático de ofertas comerciales con IA para ORECO. Automatización del proceso de cotización.',
    amount: 33900,
    currency: 'EUR',
    statusCode: 4,
    company: 'MTI',
    probability: 50,
    weightedPipeline: 16950,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-04-30',
    businessLines: { hardware: 0, ia: 33900, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 20000,
    materialCost: 2000,
    peopleCost: 18000,
    margin: 41.0,
    totalInvoiced: 0,
    pendingToInvoice: 33900,
    wipStatus: 0,
    totalPercentage: 50,
    endDate: '2026-09-30',
    observations: 'Solución IA para generación automática de propuestas.',
  },

  // ============================================================
  // STATUS 3 - REQUIREMENTS GATHERING
  // ============================================================
  {
    id: '26-468',
    client: 'GARABITO',
    date: '2026-03-20',
    opportunity: 'Smart City Garabito',
    description: 'Proyecto integral de ciudad inteligente para el municipio de Garabito en Costa Rica. Plataforma IoT, IA y gestión de servicios municipales.',
    amount: 1000000,
    currency: 'EUR',
    statusCode: 3,
    company: 'MTI',
    probability: 25,
    weightedPipeline: 250000,
    owner: 'DANI',
    country: 'Spain',
    expectedClosingDate: '2027-03-31',
    businessLines: { hardware: 500000, ia: 500000, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 650000,
    materialCost: 400000,
    peopleCost: 250000,
    margin: 35.0,
    totalInvoiced: 0,
    pendingToInvoice: 1000000,
    wipStatus: 0,
    totalPercentage: 25,
    endDate: '2028-12-31',
    observations: 'Proyecto Smart City en Centroamérica. Financiación internacional.',
  },
  {
    id: '26-421',
    client: 'New Balance',
    date: '2026-02-14',
    opportunity: 'Motor Recomendador New Balance',
    description: 'Desarrollo de motor de recomendación personalizada con IA para New Balance. Mejora de experiencia de compra y fidelización.',
    amount: 62500,
    currency: 'EUR',
    statusCode: 3,
    company: 'MTI',
    probability: 30,
    weightedPipeline: 18750,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-07-31',
    businessLines: { hardware: 0, ia: 62500, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 38000,
    materialCost: 5000,
    peopleCost: 33000,
    margin: 39.2,
    totalInvoiced: 0,
    pendingToInvoice: 62500,
    wipStatus: 0,
    totalPercentage: 30,
    endDate: '2026-12-31',
    observations: 'Motor IA recomendación para retail deportivo.',
  },
  {
    id: '26-422',
    client: 'Sisubvenciones',
    date: '2026-02-18',
    opportunity: 'Plataforma Subvenciones Sisubvenciones',
    description: 'Plataforma integral de gestión de subvenciones con IA para automatizar la búsqueda, aplicación y seguimiento de ayudas públicas.',
    amount: 74750,
    currency: 'EUR',
    statusCode: 3,
    company: 'MTI',
    probability: 35,
    weightedPipeline: 26162.5,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-08-31',
    businessLines: { hardware: 0, ia: 74750, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 45000,
    materialCost: 5000,
    peopleCost: 40000,
    margin: 39.8,
    totalInvoiced: 0,
    pendingToInvoice: 74750,
    wipStatus: 0,
    totalPercentage: 35,
    endDate: '2026-12-31',
    observations: 'Plataforma SaaS para gestión de subvenciones.',
  },
  {
    id: '26-427',
    client: 'Pazo de los Escudos',
    date: '2026-02-22',
    opportunity: 'Agente Hoteles Pazo de los Escudos',
    description: 'Agente IA conversacional para gestión hotelera de Pazo de los Escudos. Reservas, atención al cliente y optimización de operaciones.',
    amount: 54500,
    currency: 'EUR',
    statusCode: 3,
    company: 'MTI',
    probability: 40,
    weightedPipeline: 21800,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-07-31',
    businessLines: { hardware: 0, ia: 54500, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 32000,
    materialCost: 4000,
    peopleCost: 28000,
    margin: 41.3,
    totalInvoiced: 0,
    pendingToInvoice: 54500,
    wipStatus: 0,
    totalPercentage: 40,
    endDate: '2026-12-31',
    observations: 'Agente IA para sector hotelero de lujo.',
  },
  {
    id: '26-419',
    client: 'Ecoforest',
    date: '2026-02-10',
    opportunity: 'MVP Fase 2 Asistente Postventa',
    description: 'Segunda fase del asistente IA de postventa para Ecoforest. Ampliación de capacidades de soporte técnico automatizado.',
    amount: 34500,
    currency: 'EUR',
    statusCode: 3,
    company: 'MTI',
    probability: 45,
    weightedPipeline: 15525,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-06-30',
    businessLines: { hardware: 0, ia: 34500, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 20000,
    materialCost: 3000,
    peopleCost: 17000,
    margin: 42.0,
    totalInvoiced: 0,
    pendingToInvoice: 34500,
    wipStatus: 0,
    totalPercentage: 45,
    endDate: '2026-09-30',
    observations: 'Continuación exitosa MVP Fase 1.',
  },
  {
    id: '26-429',
    client: 'Porlan',
    date: '2026-02-25',
    opportunity: 'Configurador Ofertas Porlan',
    description: 'Sistema configurador de ofertas con IA para Porlan. Automatización del proceso de generación de propuestas comerciales para el sector construcción.',
    amount: 55000,
    currency: 'EUR',
    statusCode: 3,
    company: 'MTI',
    probability: 30,
    weightedPipeline: 16500,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-08-31',
    businessLines: { hardware: 0, ia: 55000, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 33000,
    materialCost: 4000,
    peopleCost: 29000,
    margin: 40.0,
    totalInvoiced: 0,
    pendingToInvoice: 55000,
    wipStatus: 0,
    totalPercentage: 30,
    endDate: '2026-12-31',
    observations: 'Configurador IA para sector materiales construcción.',
  },
  {
    id: '25-234',
    client: 'Merchant Union',
    date: '2025-08-05',
    opportunity: 'CPM MaruXIA',
    description: 'Plataforma CPM (Corporate Performance Management) con IA MaruXIA para Merchant Union. Gestión del rendimiento corporativo y analytics avanzado.',
    amount: 3000000,
    currency: 'EUR',
    statusCode: 3,
    company: 'MTI',
    probability: 20,
    weightedPipeline: 600000,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2027-06-30',
    businessLines: { hardware: 0, ia: 3000000, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 1800000,
    materialCost: 300000,
    peopleCost: 1500000,
    margin: 40.0,
    totalInvoiced: 0,
    pendingToInvoice: 3000000,
    wipStatus: 0,
    totalPercentage: 20,
    endDate: '2028-12-31',
    observations: 'Proyecto transformacional CPM con IA. Alto impacto estratégico.',
  },
  {
    id: '25-237',
    client: 'Sarawak State',
    date: '2025-08-15',
    opportunity: 'Estudio Viabilidad Fondos FIEM Sarawak',
    description: 'Estudio de viabilidad para acceso a fondos FIEM para proyectos de infraestructura digital en Sarawak, Malaysia.',
    amount: 565000,
    currency: 'EUR',
    statusCode: 3,
    company: 'MTI',
    probability: 25,
    weightedPipeline: 141250,
    owner: 'SERGIO',
    country: 'Malaysia',
    expectedClosingDate: '2026-12-31',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 565000 },
    costs: 350000,
    materialCost: 50000,
    peopleCost: 300000,
    margin: 38.1,
    totalInvoiced: 0,
    pendingToInvoice: 565000,
    wipStatus: 0,
    totalPercentage: 25,
    endDate: '2027-06-30',
    observations: 'Financiación FIEM para proyectos Sarawak. Coordinación con entidades financieras.',
  },

  // ============================================================
  // STATUS 8 - FINISHED
  // ============================================================
  {
    id: '25-156',
    client: 'Kingsway',
    date: '2025-01-20',
    opportunity: 'Fusion Center Singapore',
    description: 'Centro de fusión de datos para Kingsway en Singapore. Integración de múltiples fuentes de datos y plataforma de análisis en tiempo real.',
    amount: 245762.71,
    currency: 'EUR',
    statusCode: 8,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 245762.71,
    owner: 'FDB',
    country: 'Singapore',
    expectedClosingDate: '2025-09-30',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 245762.71 },
    acceptanceDate: '2025-02-01',
    costs: 155000,
    materialCost: 30000,
    peopleCost: 125000,
    margin: 36.9,
    totalInvoiced: 245762.71,
    pendingToInvoice: 0,
    wipStatus: 100,
    totalPercentage: 100,
    endDate: '2025-09-30',
    observations: 'Proyecto finalizado exitosamente. Cliente satisfecho.',
  },
  {
    id: '25-041',
    client: 'Unisystems',
    date: '2025-01-10',
    opportunity: 'Smart Solar Waters Heaters',
    description: 'Sistema IoT de monitorización y gestión de calentadores de agua solares inteligentes para Unisystems.',
    amount: 53660,
    currency: 'EUR',
    statusCode: 8,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 53660,
    owner: 'JORDI',
    country: 'Spain',
    expectedClosingDate: '2025-06-30',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 26830, events: 0, proservices: 26830 },
    acceptanceDate: '2025-01-15',
    costs: 35000,
    materialCost: 12000,
    peopleCost: 23000,
    margin: 34.8,
    totalInvoiced: 53660,
    pendingToInvoice: 0,
    wipStatus: 100,
    totalPercentage: 100,
    endDate: '2025-06-30',
    observations: 'Proyecto IoT completado. Documentación entregada.',
  },
  {
    id: '24-089',
    client: 'Ajuntament BCN',
    date: '2024-03-01',
    opportunity: 'Plataforma Smart Lighting BCN',
    description: 'Plataforma de gestión de alumbrado inteligente para el Ayuntamiento de Barcelona. Sistema centralizado con telegestión y analytics.',
    amount: 320000,
    currency: 'EUR',
    statusCode: 8,
    company: 'BCN',
    probability: 100,
    weightedPipeline: 320000,
    owner: 'JML',
    country: 'Spain',
    expectedClosingDate: '2024-12-31',
    businessLines: { hardware: 160000, ia: 80000, bim: 0, ttioOm: 80000, events: 0, proservices: 0 },
    acceptanceDate: '2024-03-15',
    costs: 210000,
    materialCost: 130000,
    peopleCost: 80000,
    margin: 34.4,
    totalInvoiced: 320000,
    pendingToInvoice: 0,
    wipStatus: 100,
    totalPercentage: 100,
    endDate: '2024-12-31',
    observations: 'Proyecto referencia para Smart City en Europa.',
  },
  {
    id: '24-122',
    client: 'Port de Barcelona',
    date: '2024-05-15',
    opportunity: 'Digitalización Terminal Containers',
    description: 'Digitalización completa de la terminal de contenedores del Port de Barcelona. IoT, tracking y optimización de operaciones.',
    amount: 485000,
    currency: 'EUR',
    statusCode: 8,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 485000,
    owner: 'DANI',
    country: 'Spain',
    expectedClosingDate: '2024-12-31',
    businessLines: { hardware: 200000, ia: 135000, bim: 0, ttioOm: 150000, events: 0, proservices: 0 },
    acceptanceDate: '2024-05-20',
    costs: 310000,
    materialCost: 180000,
    peopleCost: 130000,
    margin: 36.1,
    totalInvoiced: 485000,
    pendingToInvoice: 0,
    wipStatus: 100,
    totalPercentage: 100,
    endDate: '2024-12-31',
    observations: 'Gran proyecto portuario. Caso de éxito importante.',
  },

  // ============================================================
  // STATUS 2 - OPPORTUNITY
  // ============================================================
  {
    id: '25-122',
    client: 'H2LATAM',
    date: '2025-03-20',
    opportunity: 'Pulseras Personas Mayores',
    description: 'Wearables IoT para monitorización de personas mayores. Pulseras inteligentes con alertas médicas y geolocalización.',
    amount: 14500,
    currency: 'EUR',
    statusCode: 2,
    company: 'MTI',
    probability: 15,
    weightedPipeline: 2175,
    owner: 'DANI',
    country: 'Spain',
    expectedClosingDate: '2025-12-31',
    businessLines: { hardware: 14500, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 10000,
    materialCost: 9000,
    peopleCost: 1000,
    margin: 31.0,
    totalInvoiced: 0,
    pendingToInvoice: 14500,
    wipStatus: 0,
    totalPercentage: 15,
    observations: 'Oportunidad en fase inicial. Exploración de mercado.',
  },
  {
    id: '25-184',
    client: 'H2LATAM',
    date: '2025-05-10',
    opportunity: 'Instalar 2 Cargadores Electricos Semirapidos',
    description: 'Instalación de 2 cargadores eléctricos semirápidos para flota de vehículos. Incluye gestión inteligente de carga.',
    amount: 30000,
    currency: 'EUR',
    statusCode: 2,
    company: 'MTI',
    probability: 20,
    weightedPipeline: 6000,
    owner: 'JML',
    country: 'Spain',
    expectedClosingDate: '2025-12-31',
    businessLines: { hardware: 30000, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 23000,
    materialCost: 22000,
    peopleCost: 1000,
    margin: 23.3,
    totalInvoiced: 0,
    pendingToInvoice: 30000,
    wipStatus: 0,
    totalPercentage: 20,
    observations: 'Oportunidad movilidad eléctrica. Mercado en crecimiento.',
  },
  {
    id: '26-462',
    client: 'AEI',
    date: '2026-03-12',
    opportunity: 'AEI 2026 CPD',
    description: 'Proyecto CPD con financiación AEI 2026. Desarrollo de plataforma IA con ayudas de innovación empresarial.',
    amount: 0,
    currency: 'EUR',
    statusCode: 2,
    company: 'MTI',
    probability: 20,
    weightedPipeline: 0,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2026-12-31',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 0,
    materialCost: 0,
    peopleCost: 0,
    margin: 0,
    totalInvoiced: 0,
    pendingToInvoice: 0,
    wipStatus: 0,
    totalPercentage: 20,
    observations: 'Exploración convocatoria AEI 2026. Pendiente definición alcance.',
  },
  {
    id: '26-450',
    client: 'Ferrovial',
    date: '2026-02-05',
    opportunity: 'Plataforma Digital Infraestructura',
    description: 'Plataforma digital de gestión de infraestructura con gemelo digital y IA para Ferrovial.',
    amount: 450000,
    currency: 'EUR',
    statusCode: 2,
    company: 'MTI',
    probability: 15,
    weightedPipeline: 67500,
    owner: 'DANI',
    country: 'Spain',
    expectedClosingDate: '2027-06-30',
    businessLines: { hardware: 0, ia: 225000, bim: 225000, ttioOm: 0, events: 0, proservices: 0 },
    costs: 290000,
    materialCost: 50000,
    peopleCost: 240000,
    margin: 35.6,
    totalInvoiced: 0,
    pendingToInvoice: 450000,
    wipStatus: 0,
    totalPercentage: 15,
    observations: 'Gran oportunidad con Ferrovial. Presentación inicial realizada.',
  },
  {
    id: '26-453',
    client: 'Renfe',
    date: '2026-02-12',
    opportunity: 'IoT Mantenimiento Predictivo Trenes',
    description: 'Sistema IoT de mantenimiento predictivo para flota de trenes Renfe. Sensórica, telemetría y analytics predictivo.',
    amount: 890000,
    currency: 'EUR',
    statusCode: 2,
    company: 'MTI',
    probability: 10,
    weightedPipeline: 89000,
    owner: 'JML',
    country: 'Spain',
    expectedClosingDate: '2027-12-31',
    businessLines: { hardware: 445000, ia: 222500, bim: 0, ttioOm: 222500, events: 0, proservices: 0 },
    costs: 580000,
    materialCost: 380000,
    peopleCost: 200000,
    margin: 34.8,
    totalInvoiced: 0,
    pendingToInvoice: 890000,
    wipStatus: 0,
    totalPercentage: 10,
    observations: 'Licitación pública Renfe. Alta competencia.',
  },
  {
    id: '26-456',
    client: 'Endesa',
    date: '2026-02-20',
    opportunity: 'Smart Grid Analytics Platform',
    description: 'Plataforma de analytics para red eléctrica inteligente de Endesa. Predicción de demanda y gestión optimizada de distribución.',
    amount: 650000,
    currency: 'EUR',
    statusCode: 2,
    company: 'MTI',
    probability: 12,
    weightedPipeline: 78000,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2027-06-30',
    businessLines: { hardware: 0, ia: 650000, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 420000,
    materialCost: 80000,
    peopleCost: 340000,
    margin: 35.4,
    totalInvoiced: 0,
    pendingToInvoice: 650000,
    wipStatus: 0,
    totalPercentage: 12,
    observations: 'Presentación a CTO Endesa programada.',
  },

  // ============================================================
  // STATUS 9 - LOST
  // ============================================================
  {
    id: '25-175',
    client: 'OBS',
    date: '2025-04-15',
    opportunity: 'KAFD Change Request Contract CR2',
    description: 'Change request para contrato KAFD (King Abdullah Financial District). Ampliación de servicios y nuevas funcionalidades.',
    amount: 630000,
    currency: 'EUR',
    statusCode: 9,
    company: 'MTI ARABIA',
    probability: 0,
    weightedPipeline: 0,
    owner: 'THIERY',
    country: 'Saudi Arabia',
    expectedClosingDate: '2025-09-30',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 630000 },
    costs: 420000,
    materialCost: 80000,
    peopleCost: 340000,
    margin: 33.3,
    totalInvoiced: 0,
    pendingToInvoice: 0,
    wipStatus: 0,
    totalPercentage: 0,
    endDate: '2025-09-30',
    observations: 'Perdido por precio. Competidor ofreció mejor condiciones.',
  },
  {
    id: '26-418',
    client: 'UOC',
    date: '2026-01-25',
    opportunity: 'Sistemes Encastats 2026',
    description: 'Suministro de sistemas embebidos para laboratorio de la Universitat Oberta de Catalunya.',
    amount: 0,
    currency: 'EUR',
    statusCode: 9,
    company: 'MTI',
    probability: 0,
    weightedPipeline: 0,
    owner: 'OSCAR',
    country: 'Spain',
    expectedClosingDate: '2026-04-30',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 },
    costs: 0,
    materialCost: 0,
    peopleCost: 0,
    margin: 0,
    totalInvoiced: 0,
    pendingToInvoice: 0,
    wipStatus: 0,
    totalPercentage: 0,
    observations: 'Descartado por cliente. Sin presupuesto.',
  },
  {
    id: '25-190',
    client: 'Acciona',
    date: '2025-05-20',
    opportunity: 'Gestión Digital Proyectos Renovables',
    description: 'Plataforma de gestión digital para proyectos de energía renovable de Acciona. BIM y gestión del ciclo de vida.',
    amount: 520000,
    currency: 'EUR',
    statusCode: 9,
    company: 'MTI',
    probability: 0,
    weightedPipeline: 0,
    owner: 'SERGIO',
    country: 'Spain',
    expectedClosingDate: '2025-10-31',
    businessLines: { hardware: 0, ia: 130000, bim: 390000, ttioOm: 0, events: 0, proservices: 0 },
    costs: 340000,
    materialCost: 60000,
    peopleCost: 280000,
    margin: 34.6,
    totalInvoiced: 0,
    pendingToInvoice: 0,
    wipStatus: 0,
    totalPercentage: 0,
    observations: 'Perdido en licitación. Ganó empresa francesa.',
  },
  {
    id: '25-198',
    client: 'Indra',
    date: '2025-06-10',
    opportunity: 'Soporte Técnico Sistemas Defensa',
    description: 'Servicios de soporte técnico especializado para sistemas de defensa de Indra.',
    amount: 280000,
    currency: 'EUR',
    statusCode: 9,
    company: 'DIPRO',
    probability: 0,
    weightedPipeline: 0,
    owner: 'DANI',
    country: 'Spain',
    expectedClosingDate: '2025-12-31',
    businessLines: { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 280000 },
    costs: 190000,
    materialCost: 30000,
    peopleCost: 160000,
    margin: 32.1,
    totalInvoiced: 0,
    pendingToInvoice: 0,
    wipStatus: 0,
    totalPercentage: 0,
    observations: 'Perdido. Indra optó por recurso interno.',
  },

  // STATUS 6 - WON (additional)
  {
    id: '26-410',
    client: 'TMB',
    date: '2026-01-25',
    opportunity: 'Sistema Informacion Viajero Fase III',
    description: 'Tercera fase del sistema de información al viajero para TMB. Nuevos paneles de información y app móvil integrada.',
    amount: 380000,
    currency: 'EUR',
    statusCode: 6,
    company: 'BCN',
    probability: 100,
    weightedPipeline: 380000,
    owner: 'JML',
    country: 'Spain',
    expectedClosingDate: '2026-12-31',
    businessLines: { hardware: 200000, ia: 80000, bim: 0, ttioOm: 100000, events: 0, proservices: 0 },
    acceptanceDate: '2026-02-01',
    costs: 250000,
    materialCost: 160000,
    peopleCost: 90000,
    margin: 34.2,
    totalInvoiced: 0,
    pendingToInvoice: 380000,
    wipStatus: 0,
    totalPercentage: 100,
    endDate: '2026-12-31',
    observations: 'Contrato firmado. Inicio de proyecto planificado.',
  },
  {
    id: '26-415',
    client: 'Gobierno Navarra',
    date: '2026-02-05',
    opportunity: 'Smart Agriculture Navarra',
    description: 'Plataforma Smart Agriculture para la gestión inteligente del sector agrícola navarro. IoT, telemetría y analytics para optimización de cultivos.',
    amount: 290000,
    currency: 'EUR',
    statusCode: 6,
    company: 'MTI',
    probability: 100,
    weightedPipeline: 290000,
    owner: 'DANI',
    country: 'Spain',
    expectedClosingDate: '2026-12-31',
    businessLines: { hardware: 145000, ia: 72500, bim: 0, ttioOm: 72500, events: 0, proservices: 0 },
    acceptanceDate: '2026-02-10',
    costs: 185000,
    materialCost: 110000,
    peopleCost: 75000,
    margin: 36.2,
    totalInvoiced: 0,
    pendingToInvoice: 290000,
    wipStatus: 0,
    totalPercentage: 100,
    endDate: '2026-12-31',
    observations: 'Contrato ganado. Planificación en curso.',
  },
];

// ============================================================
// CLIENTS DATA
// ============================================================
export const clients: Client[] = [
  {
    id: 'c001',
    name: 'Kingsway Dynamic',
    country: 'Singapore',
    totalAmount: 3097957.63,
    totalInvoiced: 1445762.71,
    pendingToInvoice: 1652194.92,
    opportunitiesCount: 1,
    projectsCount: 2,
    primaryOwner: 'FDB',
    lastActivity: '2026-03-15',
  },
  {
    id: 'c002',
    name: 'FC Barcelona',
    country: 'Spain',
    totalAmount: 819900,
    totalInvoiced: 65000,
    pendingToInvoice: 754900,
    opportunitiesCount: 2,
    projectsCount: 1,
    primaryOwner: 'SERGIO',
    lastActivity: '2026-03-10',
  },
  {
    id: 'c003',
    name: 'Merchant Union',
    country: 'Spain',
    totalAmount: 3102100,
    totalInvoiced: 0,
    pendingToInvoice: 3102100,
    opportunitiesCount: 2,
    projectsCount: 0,
    primaryOwner: 'SERGIO',
    lastActivity: '2026-02-28',
  },
  {
    id: 'c004',
    name: 'Worldsensing',
    country: 'Spain',
    totalAmount: 230180,
    totalInvoiced: 117000,
    pendingToInvoice: 113180,
    opportunitiesCount: 2,
    projectsCount: 2,
    primaryOwner: 'JML',
    lastActivity: '2026-03-12',
  },
  {
    id: 'c005',
    name: 'SAGALES',
    country: 'Spain',
    totalAmount: 960000,
    totalInvoiced: 0,
    pendingToInvoice: 960000,
    opportunitiesCount: 1,
    projectsCount: 0,
    primaryOwner: 'JML',
    lastActivity: '2026-03-18',
  },
  {
    id: 'c006',
    name: 'GMV',
    country: 'Spain',
    totalAmount: 250080,
    totalInvoiced: 45000,
    pendingToInvoice: 205080,
    opportunitiesCount: 2,
    projectsCount: 1,
    primaryOwner: 'JML',
    lastActivity: '2026-03-10',
  },
  {
    id: 'c007',
    name: 'Telbina',
    country: 'Malaysia',
    totalAmount: 1800000,
    totalInvoiced: 0,
    pendingToInvoice: 1800000,
    opportunitiesCount: 2,
    projectsCount: 0,
    primaryOwner: 'JORDI POL',
    lastActivity: '2026-02-28',
  },
  {
    id: 'c008',
    name: 'CRCC',
    country: 'Saudi Arabia',
    totalAmount: 1620000,
    totalInvoiced: 0,
    pendingToInvoice: 1620000,
    opportunitiesCount: 2,
    projectsCount: 0,
    primaryOwner: 'CHADI',
    lastActivity: '2026-02-20',
  },
  {
    id: 'c009',
    name: 'Diputacio Tarragona',
    country: 'Spain',
    totalAmount: 1680000,
    totalInvoiced: 0,
    pendingToInvoice: 1680000,
    opportunitiesCount: 1,
    projectsCount: 0,
    primaryOwner: 'DANI',
    lastActivity: '2026-03-05',
  },
  {
    id: 'c010',
    name: 'INETUM',
    country: 'Spain',
    totalAmount: 770154,
    totalInvoiced: 0,
    pendingToInvoice: 770154,
    opportunitiesCount: 1,
    projectsCount: 0,
    primaryOwner: 'JML',
    lastActivity: '2026-02-15',
  },
  {
    id: 'c011',
    name: 'P. Freire',
    country: 'Spain',
    totalAmount: 224322.52,
    totalInvoiced: 130000,
    pendingToInvoice: 94322.52,
    opportunitiesCount: 1,
    projectsCount: 2,
    primaryOwner: 'SERGIO',
    lastActivity: '2026-03-08',
  },
  {
    id: 'c012',
    name: 'RETECH',
    country: 'Spain',
    totalAmount: 187661.25,
    totalInvoiced: 140000,
    pendingToInvoice: 47661.25,
    opportunitiesCount: 1,
    projectsCount: 1,
    primaryOwner: 'SERGIO',
    lastActivity: '2026-02-28',
  },
  {
    id: 'c013',
    name: 'SMA',
    country: 'Malaysia',
    totalAmount: 415125,
    totalInvoiced: 200000,
    pendingToInvoice: 215125,
    opportunitiesCount: 1,
    projectsCount: 1,
    primaryOwner: 'MARIA',
    lastActivity: '2026-03-01',
  },
];

// ============================================================
// EMPLOYEES DATA
// ============================================================
export const employees: Employee[] = [
  { id: 'e001', name: 'Dani Alonso', email: 'dalonso@mingothings.com', role: 'Business Development Manager', department: 'Comercial', hourlyCost: 95, activeProjects: 4, availability: 60 },
  { id: 'e002', name: 'Sergio García', email: 'sgarcia@mingothings.com', role: 'IA Solutions Lead', department: 'Tecnología', hourlyCost: 110, activeProjects: 8, availability: 20 },
  { id: 'e003', name: 'JML', email: 'jml@mingothings.com', role: 'Hardware & Transport Lead', department: 'Ingeniería', hourlyCost: 100, activeProjects: 5, availability: 30 },
  { id: 'e004', name: 'FDB', email: 'fdb@mingothings.com', role: 'APAC Director', department: 'Dirección', hourlyCost: 150, activeProjects: 2, availability: 50 },
  { id: 'e005', name: 'Jordi Pol', email: 'jpol@mingothings.com', role: 'Malaysia Business Director', department: 'Dirección', hourlyCost: 130, activeProjects: 3, availability: 40 },
  { id: 'e006', name: 'Chadi', email: 'chadi@mingothings.com', role: 'Middle East Director', department: 'Dirección', hourlyCost: 140, activeProjects: 2, availability: 45 },
  { id: 'e007', name: 'Maria', email: 'maria@mingothings.com', role: 'Events Manager', department: 'Eventos', hourlyCost: 90, activeProjects: 1, availability: 70 },
  { id: 'e008', name: 'Carles', email: 'carles@mingothings.com', role: 'Technical PM', department: 'Ingeniería', hourlyCost: 85, activeProjects: 2, availability: 55 },
  { id: 'e009', name: 'ADI', email: 'adi@mingothings.com', role: 'HR Outsourcing Lead', department: 'Recursos Humanos', hourlyCost: 80, activeProjects: 1, availability: 75 },
  { id: 'e010', name: 'Thiery', email: 'thiery@mingothings.com', role: 'ME Business Dev', department: 'Comercial', hourlyCost: 120, activeProjects: 0, availability: 90 },
  { id: 'e011', name: 'Oscar', email: 'oscar@mingothings.com', role: 'Hardware Engineer', department: 'Ingeniería', hourlyCost: 75, activeProjects: 0, availability: 95 },
  { id: 'e012', name: 'Jordi', email: 'jordi@mingothings.com', role: 'IoT Engineer', department: 'Tecnología', hourlyCost: 85, activeProjects: 1, availability: 80 },
];

// ============================================================
// MONTHLY BILLING DATA
// ============================================================
export const monthlyBilling: MonthlyBilling[] = [
  { month: 'Ene 2025', invoiced: 185000, target: 200000, collected: 175000 },
  { month: 'Feb 2025', invoiced: 220000, target: 200000, collected: 205000 },
  { month: 'Mar 2025', invoiced: 195000, target: 220000, collected: 190000 },
  { month: 'Abr 2025', invoiced: 310000, target: 220000, collected: 295000 },
  { month: 'May 2025', invoiced: 275000, target: 250000, collected: 260000 },
  { month: 'Jun 2025', invoiced: 340000, target: 280000, collected: 315000 },
  { month: 'Jul 2025', invoiced: 180000, target: 250000, collected: 170000 },
  { month: 'Ago 2025', invoiced: 145000, target: 200000, collected: 140000 },
  { month: 'Sep 2025', invoiced: 380000, target: 300000, collected: 360000 },
  { month: 'Oct 2025', invoiced: 420000, target: 350000, collected: 400000 },
  { month: 'Nov 2025', invoiced: 395000, target: 380000, collected: 370000 },
  { month: 'Dic 2025', invoiced: 510000, target: 450000, collected: 485000 },
  { month: 'Ene 2026', invoiced: 290000, target: 350000, collected: 270000 },
  { month: 'Feb 2026', invoiced: 320000, target: 350000, collected: 300000 },
  { month: 'Mar 2026', invoiced: 410000, target: 400000, collected: 380000 },
  { month: 'Abr 2026', invoiced: 350000, target: 420000, collected: 325000 },
];

// ============================================================
// COMPUTED HELPERS
// ============================================================
export function getKpiData() {
  const active = opportunities.filter(o => o.statusCode !== 9);
  const delivering = opportunities.filter(o => o.statusCode === 7);
  const finished = opportunities.filter(o => o.statusCode === 8);
  const open = opportunities.filter(o => [2, 3, 4, 5].includes(o.statusCode));
  const lost = opportunities.filter(o => o.statusCode === 9);
  const won = opportunities.filter(o => [6, 7, 8].includes(o.statusCode));

  const totalPipeline = active.reduce((s, o) => s + o.amount, 0);
  const weightedPipeline = active.reduce((s, o) => s + o.weightedPipeline, 0);
  const totalAccepted = won.reduce((s, o) => s + o.amount, 0);
  const totalInvoiced = opportunities.reduce((s, o) => s + o.totalInvoiced, 0);
  const totalPending = opportunities.reduce((s, o) => s + o.pendingToInvoice, 0);

  return {
    totalPipeline,
    weightedPipeline,
    totalAccepted,
    totalInvoiced,
    totalPending,
    deliveringCount: delivering.length,
    finishedCount: finished.length,
    openCount: open.length,
    lostCount: lost.length,
    totalAmount: totalInvoiced + totalPending,
  };
}

export function getPipelineByStatus() {
  const statusGroups: Record<number, { count: number; amount: number; label: string }> = {};
  opportunities.forEach(o => {
    if (!statusGroups[o.statusCode]) {
      statusGroups[o.statusCode] = { count: 0, amount: 0, label: '' };
    }
    statusGroups[o.statusCode].count++;
    statusGroups[o.statusCode].amount += o.amount;
  });
  return Object.entries(statusGroups).map(([code, data]) => ({
    status: getStatusLabel(Number(code)),
    count: data.count,
    amount: data.amount,
    code: Number(code),
  }));
}

export function getBusinessLineDistribution() {
  const totals = { hardware: 0, ia: 0, bim: 0, ttioOm: 0, events: 0, proservices: 0 };
  opportunities
    .filter(o => o.statusCode !== 9)
    .forEach(o => {
      totals.hardware += o.businessLines.hardware;
      totals.ia += o.businessLines.ia;
      totals.bim += o.businessLines.bim;
      totals.ttioOm += o.businessLines.ttioOm;
      totals.events += o.businessLines.events;
      totals.proservices += o.businessLines.proservices;
    });
  return [
    { name: 'Hardware', value: totals.hardware, fill: '#f59e0b' },
    { name: 'IA', value: totals.ia, fill: '#3b82f6' },
    { name: 'BIM', value: totals.bim, fill: '#8b5cf6' },
    { name: 'TTIO/O&M', value: totals.ttioOm, fill: '#10b981' },
    { name: 'Eventos', value: totals.events, fill: '#f97316' },
    { name: 'Pro Services', value: totals.proservices, fill: '#06b6d4' },
  ].filter(d => d.value > 0);
}

export function getPipelineByCompany() {
  const companies: Record<string, number> = {};
  opportunities
    .filter(o => o.statusCode !== 9)
    .forEach(o => {
      companies[o.company] = (companies[o.company] || 0) + o.amount;
    });
  return Object.entries(companies).map(([name, amount]) => ({ name, amount }));
}

export function getTopClients(n = 5) {
  return [...clients]
    .sort((a, b) => b.totalAmount - a.totalAmount)
    .slice(0, n);
}

function getStatusLabel(code: number): string {
  const labels: Record<number, string> = {
    2: 'Oportunidad',
    3: 'Req. Gathering',
    4: 'Solution Def.',
    5: 'Neg. Contrato',
    6: 'Ganado',
    7: 'Delivering',
    8: 'Finalizado',
    9: 'Perdido',
  };
  return labels[code] || `Status ${code}`;
}
